### ISSUE TITLE
Credenziali anche per Ice server

### ISSUE THREAD

**Issue by robyanne92** [robyanne92/IceMartini#2]
Dovremmo sentirci per definire meglio la modifica che ci ha anticipato Massimo sulle credenziali per accedere al server ice.

**Comment by robyanne92** [comment]
Introdurre un file di configurazione dove salvare delle credenziali. Il server deve accettare la connessione solo nel caso in cui dovesse ricevere le credenziali corrette da parte del client.

**Comment by ChristianBar** [comment]
Mi chiedevo questo:
https://github.com/robyanne92/ueberreticiplaghin/issues/9#issuecomment-600150355

**Comment by robyanne92** [comment]
Se i test sono andati a buon fine && non c'è altro da implementare fatemi sapere così chiudo...

**Comment by ChristianBar** [comment]
> Se i test sono andati a buon fine && non c'è altro da implementare fatemi sapere così chiudo...

chiudi, chiudi :)
